app:
  name: reddit-auto-post

server:
  host: localhost
  port: 8000

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 
  name: test

reddit:
  url: https://www.reddit.com/api
  oauth: https://oauth.reddit.com/api